name: Send email on push to main

on:
  push:
    branches: [ main ]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Send email
    
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        ACTIONS_STEP_DEBUG: true
      run: |
        python send_email.py
      continue-on-error: true
        
    - if: ${{ always() }}
      name: Show Python script output
      run: echo ::set-output name=python_output::$(cat send_email.log)
      id: python_output
